version: '3.8'

services:
  ubuntu:
    image: techcaotri/pandoc-python:latest
    container_name: pandoc-python
    volumes:
      - ./work_shared:/work_shared
      - /etc/localtime:/etc/localtime:ro
    networks:
      - ubuntu_network
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    entrypoint: /bin/bash

networks:
  ubuntu_network:
    name: ubuntu_network
    driver: bridge
  
volumes:
  ssh-keys: