name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build the stack
        run: ./prepare_docker.sh
      - name: Publish EPUB
        run: ./publish_epub_in_docker.sh
      - name: Get Name of Artifact
        run: |
          ACTIONS_ALLOW_UNSECURE_COMMANDS=true
          ARTIFACT_PATHNAME=$(ls ./work_shared/output/*.epub | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo ::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}
          echo ::set-env name=ARTIFACT_PATHNAME::${ARTIFACT_PATHNAME}
      - name: Upload EPUB to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          repo_token: ${{ github.token }}
          file: ${{ env.ARTIFACT_PATHNAME }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "Release EPUB"
