name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build the stack
        run: ./prepare_docker.sh
      - name: Publish EPUB
        run: ./publish_epub_in_docker.sh
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release 1.0
          tag_name: 1.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Get Name of Artifact
        run: |
          ARTIFACT_PATHNAME=$(ls output/*.epub | head -n 1)
          ARTIFACT_NAME=$(basename $ARTIFACT_PATHNAME)
          echo ::set-env name=ARTIFACT_NAME::${ARTIFACT_NAME}
          echo ::set-env name=ARTIFACT_PATHNAME::${ARTIFACT_PATHNAME}
      - name: Upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_PATHNAME }}
          asset_name: ${{ env.ARTIFACT_NAME }}
          asset_content_type: application/epub+zip